### ISSUE TITLE
[1.16.3] Forge crashes on load.

### ISSUE THREAD

**Issue by Rover656** [Tfarcenim/Enchanted-Book-Redesign#7]
Crash details:
```
java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.client.renderer.RenderType
	at net.minecraft.client.gui.fonts.EmptyGlyph.<init>(SourceFile:10) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.fonts.Font.<clinit>(SourceFile:27) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.fonts.FontResourceManager.<init>(SourceFile:48) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:438) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) ~[1.16.3.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.3-34.1.5.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {re:classloading}
```

**Comment by Tfarcenim** [comment]
Full log needed

**Comment by Rover656** [comment]
Here is the full log: https://pastebin.com/pjzZ5Ksm

**Comment by Tfarcenim** [comment]
I meant latest.log or debug.log

**Comment by Rover656** [comment]
Sorry; here's latest.log https://pastebin.com/KxdGbWpc
